language: minimal
services: docker
before_install:
  - docker -v && docker-compose -v
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L https://github.com/docker/compose/releases/download/1.25.5/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - mkdir ${HOME}/.kube
  - echo "$KUBE_CONFIG" | base64 -d > ${HOME}/.kube/config
install:
  - echo 'Docker compose build'
  - docker-compose -f course-02/exercises/udacity-c3-deployment/docker/docker-compose-build.yaml build
  - echo 'Docker push '
  - docker push nilesim/udacity-restapi-user
  - docker push nilesim/udacity-restapi-feed
  - docker push nilesim/udacity-frontend
  - docker push nilesim/reverseproxy
  - echo 'kubectl start'
  - kubectl apply -f course-02/exercises/udacity-c3-deployment/k8s/backend-feed-service.yaml --record
  - kubectl apply -f course-02/exercises/udacity-c3-deployment/k8s/backend-user-service.yaml --record
  - kubectl apply -f course-02/exercises/udacity-c3-deployment/k8s/frontend-service.yaml --record
  - kubectl apply -f course-02/exercises/udacity-c3-deployment/k8s/reverseproxy-service.yaml --record
  - kubectl apply -f course-02/exercises/udacity-c3-deployment/k8s/env-configmap.yaml --record
  - kubectl apply -f course-02/exercises/udacity-c3-deployment/k8s/backend-feed-deployment.yaml --record
  - kubectl apply -f course-02/exercises/udacity-c3-deployment/k8s/backend-user-deployment.yaml --record
  - kubectl apply -f course-02/exercises/udacity-c3-deployment/k8s/frontend-deployment.yaml --record
  - kubectl apply -f course-02/exercises/udacity-c3-deployment/k8s/reverseproxy-deployment.yaml --record